name: Storage Integration Tests Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'build/storage/**'
jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Check virtualization'
        run: |
          lscpu | grep -i virtualization
      - name: 'Check kvm'
        run: |
          lsmod | grep -i kvm
      - name: 'Run Storage Integration Tests'
        working-directory: ./build/storage/tests/it
        run: |
          chmod -R 777 run.sh
          ./run.sh
