name: Storage Unit and Integration test
on:
  push:
    branches:
    - main
    - storage_integration_test
  pull_request:
    branches:
    - main
jobs:
  docker:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Run Storage Integration Tests'
        working-directory: ./build/storage/tests/it
        run: |
          lscpu | grep -i virtualization
          echo 1 > /proc/sys/kernel/sysrq
          echo x > /proc/sysrq-trigger
          lsmod | grep -i kvm
          sudo modprobe kvm-intel
          chmod -R 777 run.sh    
